datacuts:
  kmax: 0.5
  kmin: 0.001
  logit: True
  standardize: True
  ampnorm: False
  offset_amp: 1.e+4

analysis:
  seed: 0
  train_fraction: 0.85
  validation_fraction: 0.06
  alg: snpe
  suffix: ""
