datacuts:
  kmax: 0.5
  kmin: 0.15
  logit: True
  standardize: True
  ampnorm: False
  # offset_amp: 1.e+4
  offset_amp: 0.
  splits: 4
  nsubs: 1

analysis:
  seed: 0
  train_fraction: 0.85
  validation_fraction: 0.06
  alg: snle
  prior_offset: 0.2
  suffix: ""
